### ISSUE TITLE
always says "a few seconds ago"

### ISSUE THREAD

**Issue by cheshire137** [seidtgeist/ng-time-relative#5]
I can't get it to produce any output other than "a few seconds ago", even for the 1999 example. I'm using moment 2.2.1, AngularJS 1.2.1, and I initialized ng-time-relative like this:

```
cloudy_app = angular.module('CloudyApp', ['ngRoute', 'ngAnimate', 'ngCookies', 'angularMoment', 'ui.bootstrap', 'pascalprecht.translate', 'ui.select2', 'chieffancypants.loadingBar', 'ngSanitize', 'timeRelative'])
```

I tried removing `angularMoment` and I still only get "a few seconds ago" for `%time{relative: ''} 1999`.

**Comment by seidtgeist** [comment]
Have you tried putting the 1999 into the time element's datetime attribute instead?

**Comment by agzam** [comment]
Yup, it's not working :(

I ended up using moment itself... doing something like this 

{{ moment("1945", "YYYY").fromNow() }}

It's not beautiful, yet works. In order to use moment directly in the markup, moment itself needs to be exposed to the rootScope:

app.run ($rootScope)-> $rootScope.moment = moment

**Comment by tommhuth** [comment]
I had the same problem, though using the datetime attribute fixed it. Looks like it fails using the text content of the node.
